# Cramer's Rule

For the following systems of linear equations, find:

* the terms that build up the determinant of $A$
* the terms that build up the determinants of $A_{k \leftarrow \mathbf b}$
* vector of solutions
* cofactor matrix
* inverse matrix

1. $\begin{cases}
x_1 + x_2 = 2 \\
x_1 - x_2 = 0 \\
\end{cases}$

2. $\begin{cases}
x_1 - x_2 = 1 \\
3x_1 + 2x_2 = 8 \\
\end{cases}$

3. $\begin{cases}
x_1 + x_2 + x_3 = 2 \\
x_1 - x_2 + 3 x_3 = 0 \\
x_1 + 2 x_2 + 2 x_3 = 3
\end{cases}$

4. $\begin{cases}
2 x_1 + x_2 + x_3 = 1 \\
x_1 + x_2 = 0 \\
x_2 + x_3 = 1 \\
\end{cases}$

In [2]:
import numpy as np
import os
import json_tricks
from pathlib import Path

answer = {
    "task1": {
        "A": np.array([[1, 1], [1, -1]]),
        "b": np.array([[2], [0]]),
        "det_A_terms": [-1, -1],
        "det_A_k_terms": {
            0: [-2, 0],
            1: [-2, 0],
        },
        "x": np.array([[1], [1]]),
        "cofactors": np.array([[-1, -1], [-1, 1]]),
        "inverse": np.array([[0.5, 0.5], [0.5, -0.5]])
    },
    "task2": {
        "A": np.array([[1, -1], [3, 2]]),
        "b": np.array([[1], [8]]),
        "det_A_terms": [2, 3],
        "det_A_k_terms": {
            0: [2, 8],
            1: [-3, 8],
        },
        "x": np.array([[2], [1]]),
        "cofactors": np.array([[2, -3], [1, 1]]),
        "inverse": np.array([[0.4, 0.2], [-0.6, 0.2]])
    },
    "task3": {
        "A": np.array([[1, 1, 1], [1, -1, 3], [1, 2, 2]]),
        "b": np.array([[2], [0], [3]]),
        "det_A_terms": [-6, -2, -2, 1, 2, 3],
        "det_A_k_terms": {
            0: [-12, -4, 0, 0, 3, 9],
            1: [-9, -4, 0, 0, 3, 6],
            2: [-3, -3, 0, 0, 2, 4],
        },
        "x": np.array([[1], [1], [0]]),
        "cofactors": np.array([[-8, 1, 3], [0, 1, -1], [4, -2, -2]]),
        "inverse": np.array([[2, 0, -1], [-0.25, -0.25, 0.5], [-0.75, 0.25, 0.5]])
    },
    "task4": {
        "A": np.array([[2, 1, 1], [1, 1, 0], [0, 1, 1]]),
        "b": np.array([[1], [0], [1]]),
        "det_A_terms": [-1, 0, 0, 0, 1, 2],
        "det_A_k_terms": {
            0: [-1, 0, 0, 0, 0, 1],
            1: [-1, 0, 0, 0, 0, 1],
            2: [-1, 0, 0, 0, 1, 2],
        },
        "x": np.array([[0], [0], [1]]),
        "cofactors": np.array([[1, -1, 1], [0, 2, -2], [-1, 1, 1]]),
        "inverse": np.array([[0.5, 0, -0.5], [-0.5, 1, 0.5], [0.5, -1, 0.5]])
    }
}

for task_id in answer:
    print(f'=== {task_id} ===')
    one_answer = answer[task_id]
    A = one_answer['A']
    b = one_answer['b']
    x = one_answer['x']
    A_inv = one_answer['inverse']
    det = sum(one_answer['det_A_terms'])
    cofactors = one_answer['cofactors']
    det_A_k = np.array([[sum(v) for k, v in one_answer['det_A_k_terms'].items()]]).T

    print(A @ A_inv, '<- A @ A_inv (shold be I)')
    print(cofactors.T / det - A_inv, '<- C.T / det - A_inv (should be 0)')
    print(A @ x - b, '<- A @ x - b (should be 0 vector)')
    print(x - det_A_k / det, '<- x - det_A_k / det (should be 0 vector)')

json_tricks.dump(
    answer, 
    '.answer.json')

=== task1 ===
[[1. 0.]
 [0. 1.]] <- A @ A_inv (shold be I)
[[0. 0.]
 [0. 0.]] <- C.T / det - A_inv (should be 0)
[[0]
 [0]] <- A @ x - b (should be 0 vector)
[[0.]
 [0.]] <- x - det_A_k / det (should be 0 vector)
=== task2 ===
[[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]] <- A @ A_inv (shold be I)
[[0. 0.]
 [0. 0.]] <- C.T / det - A_inv (should be 0)
[[0]
 [0]] <- A @ x - b (should be 0 vector)
[[0.]
 [0.]] <- x - det_A_k / det (should be 0 vector)
=== task3 ===
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <- A @ A_inv (shold be I)
[[ 0. -0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] <- C.T / det - A_inv (should be 0)
[[0]
 [0]
 [0]] <- A @ x - b (should be 0 vector)
[[0.]
 [0.]
 [0.]] <- x - det_A_k / det (should be 0 vector)
=== task4 ===
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <- A @ A_inv (shold be I)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] <- C.T / det - A_inv (should be 0)
[[0]
 [0]
 [0]] <- A @ x - b (should be 0 vector)
[[0.]
 [0.]
 [0.]] <- x - det_A_k / det (should be 0 vecto

'{"task1": {"A": {"__ndarray__": [[1, 1], [1, -1]], "dtype": "int64", "shape": [2, 2], "Corder": true}, "b": {"__ndarray__": [[2], [0]], "dtype": "int64", "shape": [2, 1], "Corder": true}, "det_A_terms": [-1, -1], "det_A_k_terms": {"0": [-2, 0], "1": [-2, 0]}, "x": {"__ndarray__": [[1], [1]], "dtype": "int64", "shape": [2, 1], "Corder": true}, "cofactors": {"__ndarray__": [[-1, -1], [-1, 1]], "dtype": "int64", "shape": [2, 2], "Corder": true}, "inverse": {"__ndarray__": [[0.5, 0.5], [0.5, -0.5]], "dtype": "float64", "shape": [2, 2], "Corder": true}}, "task2": {"A": {"__ndarray__": [[1, -1], [3, 2]], "dtype": "int64", "shape": [2, 2], "Corder": true}, "b": {"__ndarray__": [[1], [8]], "dtype": "int64", "shape": [2, 1], "Corder": true}, "det_A_terms": [2, 3], "det_A_k_terms": {"0": [2, 8], "1": [-3, 8]}, "x": {"__ndarray__": [[2], [1]], "dtype": "int64", "shape": [2, 1], "Corder": true}, "cofactors": {"__ndarray__": [[2, -3], [1, 1]], "dtype": "int64", "shape": [2, 2], "Corder": true}, "i