# Systems of Linear Equations (SLEs) in Matrix Form

For the following systems of linear equations:

1. $\begin{cases}
x_1 + x_2 = 17 \\
2 x_1 + x_2 = 10
\end{cases}$

2. $\begin{cases}
x + 5 y = 2 \\
2 x + 9 y = 4
\end{cases}$

3. $\begin{cases}
x_1 + x_3 = 3 \\
2 x_1 + x_2 - x_3 = 2 \\
3 x_1 + x_2 - 2 x_3 = 3 \\
\end{cases}$

4. $\begin{cases}
x_1 + x_2 + x_3 + x_4 = 4 \\
2 x_1 + x_2 + x_3 + x_4 = 5 \\
3 x_1 + 2 x_2 + x_3 + x_4 = 7 \\
4 x_1 + 3 x_2 + 2 x_3 + x_4 = 10
\end{cases}$
 
Do:
    
1. Write the system of linear equations in matrix form
    
2. Using Gaussian Elimination solve the following system of equations, find 
    
    1. inverse of left-side matrix
    
    2. LU decomposition of it (using Gaussian Elimination without permutations).
    
    3. Solution of the SLE

3. Check whether the inverse matrix, PLU decomposition and SLE solution are correct: $A = LU$, $A^{-1} A = I$, $A \mathbf x = \mathbf b$

In [8]:
import numpy as np
import json_tricks

answer = {
    'task1': {
        'A': np.array([
            [1, 1],
            [2, 1]
        ], dtype=np.int64), # Changed to int64
        'y': np.array([
            [17],
            [10]
        ], dtype=np.int64), # Changed to int64
        'x': np.array([
            [-7],
            [24]
        ], dtype=np.int64), # Changed to int64
        'inverse': np.array([
            [-1, 1],
            [2, -1]
        ], dtype=np.int64), # inverse can have floats, so keep float64
        'L': np.array([
            [1, 0],
            [2, 1]
        ], dtype=np.int64), # Changed to int64
        'U': np.array([
            [1, 1],
            [0, -1]
        ], dtype=np.int64)      # Changed to int64
    },
    'task2': {
        'A': np.array([
            [1, 5],
            [2, 9]
        ], dtype=np.int64), # Changed to int64
        'y': np.array([
            [2],
            [4]
        ], dtype=np.int64), # Changed to int64
        'x': np.array([
            [2],
            [0]
        ], dtype=np.int64), # Changed to int64
        'inverse': np.array([
            [-9, 5],
            [2, -1]
        ], dtype=np.int64), # inverse can have floats, so keep float64
        'L': np.array([
            [1, 0],
            [2, 1]
        ], dtype=np.int64), # Changed to int64
        'U': np.array([
            [1, 5],
            [0, -1]
        ], dtype=np.int64)      # Changed to int64
    },
    'task3': {
        'A': np.array([
            [1, 0, 1],
            [2, 1, -1],
            [3, 1, -2]
        ], dtype=np.int64), # Changed to int64
        'y': np.array([
            [3],
            [2],
            [3]
        ], dtype=np.int64), # Changed to int64
        'x': np.array([
            [2],
            [-1],
            [1]
        ], dtype=np.int64), # Changed to int64
        'inverse': np.array([
            [0.5, -0.5, 0.5],
            [-0.5, 2.5, -1.5],
            [0.5, 0.5, -0.5]
        ], dtype=np.float64), # This inverse definitely needs float64
        'L': np.array([
            [1, 0, 0],
            [2, 1, 0],
            [3, 1, 1]
        ], dtype=np.int64), # Changed to int64
        'U': np.array([
            [1, 0, 1],
            [0, 1, -3],
            [0, 0, -2]
        ], dtype=np.int64)      # Changed to int64
    },
    'task4': {
        'A': np.array([
            [1, 1, 1, 1],
            [2, 1, 1, 1],
            [3, 2, 1, 1],
            [4, 3, 2, 1]
        ], dtype=np.int64), # Changed to int64
        'y': np.array([
            [4],
            [5],
            [7],
            [10]
        ], dtype=np.int64), # Changed to int64
        'x': np.array([
            [1],
            [1],
            [1],
            [1]
        ], dtype=np.int64), # Changed to int64
        'inverse': np.array([
            [-1, 1, 0, 0],
            [1, -2, 1, 0],
            [0, 1, -2, 1],
            [1, 0, 1, -1]
        ], dtype=np.int64), # inverse can have floats, so keep float64
        'L': np.array([
            [1, 0, 0, 0],
            [2, 1, 0, 0],
            [3, 1, 1, 0],
            [4, 1, 1, 1]
        ], dtype=np.float64), # L for task4 had integer values, but was expected float64, keeping float64
        'U': np.array([
            [1, 1, 1, 1],
            [0, -1, -1, -1],
            [0, 0, -1, -1],
            [0, 0, 0, -1]
        ], dtype=np.float64) # U for task4 had integer values, but was expected float64, keeping float64
    }
}

for task_name in answer:
    A = answer[task_name]['A']
    A_inv = answer[task_name]['inverse']
    y = answer[task_name]['y']
    x = answer[task_name]['x']
    L = answer[task_name]['L']
    U = answer[task_name]['U']
    print(f'=== {task_name} ===')
    print(A @ A_inv, '<- A @ A_inv (should be I)')
    print(A @ x - y, '<- A @ x - y (should be 0 vector)')
    print(L @ U - A, '<- L @ U - A (should be 0 matrix)')

json_tricks.dump(answer, '.answer.json')

=== task1 ===
[[1 0]
 [0 1]] <- A @ A_inv (should be I)
[[0]
 [0]] <- A @ x - y (should be 0 vector)
[[0 0]
 [0 0]] <- L @ U - A (should be 0 matrix)
=== task2 ===
[[1 0]
 [0 1]] <- A @ A_inv (should be I)
[[0]
 [0]] <- A @ x - y (should be 0 vector)
[[0 0]
 [0 0]] <- L @ U - A (should be 0 matrix)
=== task3 ===
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <- A @ A_inv (should be I)
[[0]
 [0]
 [0]] <- A @ x - y (should be 0 vector)
[[0 0 0]
 [0 0 0]
 [0 0 0]] <- L @ U - A (should be 0 matrix)
=== task4 ===
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] <- A @ A_inv (should be I)
[[0]
 [0]
 [0]
 [0]] <- A @ x - y (should be 0 vector)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] <- L @ U - A (should be 0 matrix)


'{"task1": {"A": {"__ndarray__": [[1, 1], [2, 1]], "dtype": "int64", "shape": [2, 2], "Corder": true}, "y": {"__ndarray__": [[17], [10]], "dtype": "int64", "shape": [2, 1], "Corder": true}, "x": {"__ndarray__": [[-7], [24]], "dtype": "int64", "shape": [2, 1], "Corder": true}, "inverse": {"__ndarray__": [[-1, 1], [2, -1]], "dtype": "int64", "shape": [2, 2], "Corder": true}, "L": {"__ndarray__": [[1, 0], [2, 1]], "dtype": "int64", "shape": [2, 2], "Corder": true}, "U": {"__ndarray__": [[1, 1], [0, -1]], "dtype": "int64", "shape": [2, 2], "Corder": true}}, "task2": {"A": {"__ndarray__": [[1, 5], [2, 9]], "dtype": "int64", "shape": [2, 2], "Corder": true}, "y": {"__ndarray__": [[2], [4]], "dtype": "int64", "shape": [2, 1], "Corder": true}, "x": {"__ndarray__": [[2], [0]], "dtype": "int64", "shape": [2, 1], "Corder": true}, "inverse": {"__ndarray__": [[-9, 5], [2, -1]], "dtype": "int64", "shape": [2, 2], "Corder": true}, "L": {"__ndarray__": [[1, 0], [2, 1]], "dtype": "int64", "shape": [2, 